# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "upliftgames/wally@0.3.2"
rojo = "rojo-rbx/rojo@7.4.4"
lune = "lune-org/lune@0.8.9"
selene = "kampfkarren/selene@0.27.1"
luau-lsp = "johnnymorganz/luau-lsp@1.36.0"
stylua = "johnnymorganz/stylua@2.0.1"
wally-package-types = "johnnymorganz/wally-package-types@1.3.2"
darklua = "seaofvoices/darklua@0.14.1"
pesde = "pesde-pkg/pesde@0.5.0-rc.18"
